# Generated by Django 6.0.6 on 2026-07-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_comment_options_rename_comment_comment_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='toxicity_label',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
